name: Go

on:
  push:
    branches: [ master-v ]
  pull_request:
    branches: [ master-v ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

  

    - name: Build
      run: |
       pwd
       #start make.bat
       #go build -v ./...

       $env: GOPATH=D:\a\frpu\frpu

       #cd %~dp0

       go fmt ./src/...

       $env: version=0.13.0

       #echo.

       echo 开始编译Windows 32位系统的程序

       $env: GOOS=windows

       $env: GOARCH=386

       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%/%version%/frps.exe ./src/cmd/frps

       echo 编译完成

       #echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%/%version%/frpc.exe ./src/cmd/frpc/main.go

       echo 编译完成

       #echo.

       echo 开始编译Linux 32位系统的程序

       $env: GOOS=linux

       $env: GOARCH=386
 
       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%/%version%/frps ./src/cmd/frps/main.go

       echo 编译完成

       #echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%/%version%/frpc ./src/cmd/frpc/main.go

       echo 编译完成

       # echo.

       echo 开始编译Linux arm系统的程序

       $env: GOOS=linux

       $env: GOARCH=arm
 
       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frps ./src/cmd/frps/main.go

       echo 编译完成

       #echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frpc ./src/cmd/frpc/main.go

       echo 编译完成

       #echo.

       echo 开始编译Linux mips系统的程序

       $env: GOOS=linux

       $env: GOARCH=mips

       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frps ./src/cmd/frps/main.go

       echo 编译完成

       #echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frpc ./src/cmd/frpc/main.go

       echo 编译完成

       #echo.

       echo 开始编译Linux mipsle系统的程序

       $env: GOOS=linux

       $env: GOARCH=mipsle

       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frps ./src/cmd/frps/main.go

       echo 编译完成

       # echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frpc ./src/cmd/frpc/main.go
      
       echo 编译完成

       # echo.

       echo 开始编译MAC 32位系统的程序

       $env: GOOS=darwin

       $env: GOARCH=386

       #echo.

       echo 开始编译服务端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frps ./src/cmd/frps/main.go

       echo 编译完成

       #echo.

       echo 开始编译客户端...

       go build -o bin/%GOOS%-%GOARCH%/%version%/frpc ./src/cmd/frpc/main.go

       echo 编译完成

       #echo.

       echo ---end---

       #pause>nul

    - name: Test
      run: |
        ls
      #go test -v ./...
